version: '3.8'
services:
  notification-app:
    build: ./notification-impl
    container_name: notification-app
    ports:
      - "9002:8070"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_SERVERS}"
      SPRING_MAIL_USERNAME: "${SPRING_MAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${SPRING_MAIL_PASSWORD}"
      APP_KAFKA_TOPIC: "${NOTIFICATION_TOPIC}"
      DEBUG: "${APP_DEBUG}"