services:
  app:
    build: ./notification-impl
    ports:
      - "9002:8070"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9094
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}