spring:
  application:
    name: notification

  mail:
    host: ${SPRING_MAIL_HOST:smtp.mail.ru}
    port: ${SPRING_MAIL_PORT:465}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: false
      mail.smtp.ssl.enable: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

app:
  kafka:
    topic: ${NOTIFICATION_TOPIC:notification.message.in}

debug: ${APP_DEBUG:false}